services:
  react:
    build: react
    image: react-image
    container_name: react-container
    ports:
      - "5173:5173"
    volumes:
      - ./react/frontend:/home/frontend/src
      - /home/frontend/node_modules    # Keep container’s node_modules
    working_dir: /home/frontend
    command: bash -c "yarn dev --host 0.0.0.0 --port 5173"
    restart: always


volumes:
  react-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/react/frontend
      o: bind